config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:new, :show] do
    resources :items, except: [:new] do
      post 'orders', to: 'orders#create'
      resources :includes, only: [:create, :destroy] do
        post 'without', to: 'orders#without'
        delete 'remove_without', to: 'orders#remove_without'
        post 'add', to: 'orders#add'
        delete 'remove_add', to: 'orders#remove_add'
      end
    end
  end
  resources :ingredients, except: [:new, :show]
  resources :orders, only: [:destroy]
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items

	validates :name, presence: true, uniqueness: true
end

app/models/include.rb
class Include < ApplicationRecord
	belongs_to :ingredient
	belongs_to :item
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :includes
	has_many :items, through: :includes

	validates :name, :code, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :includes
	has_many :ingredients, through: :includes
	belongs_to :category

	validates :name, :code, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :item, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_orders
  protect_from_forgery with: :exception

  $modifications = []
  def get_orders
    @orders = Order.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # No need to have comments that state what the method is doing unless the name is unclear.
  # Yours follow convention so no need!
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @categories = Category.all
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_items_path(@category), notice: 'Menu category created!'
    end
    render :index
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_items_path(@category), notice: 'Category updated!'
    end
    render :edit
  end

  def destroy
    @category = Category.find(params[:id])
    @items = @category.items.all
    # delete items in the category
    @items.each do |item|
      # deletes all includes of item
      @includes = item.includes.all
      @includes.each do |include|
        include.destroy
      end
      item.destroy
    end
    @category.destroy

    redirect_to categories_path, notice: 'Category deleted.'
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/includes_controller.rb
class IncludesController < ApplicationController

  # add include to a menu item
  def create
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:item_id])
    @include = @item.includes.create!(include_params)

    redirect_to category_item_path(@category, @item), notice: 'Ingredient added!'
  end

  # remove an include from a menu item
  def destroy
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:item_id])
    @include = Include.find_by(item_id: params[:item_id], ingredient_id: params[:id])
    @include.destroy

    redirect_to category_item_path(@category, @item), notice: 'Ingredient removed.'
  end

  private
  def include_params
    params.require(:include).permit(:ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # No need to add return after redirect_to
  def index
    @ingredients = Ingredient.all.sort_by{ |k| k["name"] }
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredients = Ingredient.all
    if @ingredient.save
      redirect_to ingredients_path, notice: 'Ingredient added!'
    end
    render :index
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path, notice: 'Ingredient updated!'
    end
    render :edit
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to ingredients_path, notice: 'Ingredient deleted.'
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :code)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @items = @category.items.all
    @item = @category.items.new
  end

  def show
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:id])
    @includes = @item.ingredients.all.sort_by{ |k| k["name"] }
    @ingredients = Ingredient.all.sort_by{ |k| k["name"] }


    # used for includes#create
    @include = @item.includes.new
    # used for orders#create
    @order = Order.new
  end

  def create
    @category = Category.find(params[:category_id])
    @items = @category.items.all
    @item = @category.items.new(item_params)
    if @item.save
      redirect_to category_items_path(@category), notice: 'Menu item created!'
    end
    render :index
  end

  def edit
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to category_item_path(@category, @item), notice: 'Menu item updated!'
    end
    render :edit
  end

  # delete menu item
  def destroy
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:id])
    @includes = @item.includes.all
    @includes.each do |include|
      include.destroy
    end
    @item.destroy

    redirect_to category_items_path(@category), notice: 'Menu item deleted.'
  end

  private
  def item_params
    params.require(:item).permit(:name, :code)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:item_id])
    @order = Order.create!(order_params)
    $modifications = []

    redirect_to category_item_path(@category, @item), notice: 'Item added to order'
  end

  def without
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:item_id])
    @ingredient = Ingredient.find(params[:include_id])
    $modifications.push('NO ' + @ingredient.name)

    redirect_to category_item_path(@category, @item), notice: 'Without ingredient'
  end

  def remove_without
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:item_id])
    @ingredient = Ingredient.find(params[:include_id])
    $modifications.delete('NO ' + @ingredient.name)

    redirect_to category_item_path(@category, @item)
  end

  def add
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:item_id])
    @ingredient = Ingredient.find(params[:include_id])
    $modifications.push('ADD ' + @ingredient.name)

    redirect_to category_item_path(@category, @item), notice: 'Add ingredient'
  end

  def remove_add
    @category = Category.find(params[:category_id])
    @item = @category.items.find(params[:item_id])
    @ingredient = Ingredient.find(params[:include_id])
    $modifications.delete('ADD ' + @ingredient.name)

    redirect_to category_item_path(@category, @item)
  end


  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to root_path
  end

  private
  def order_params
    params.require(:order).permit(:message).merge(item: @item.name, modification: $modifications)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<section class='heading_section'>
  <a href='<%= categories_path %>'>
    <div class='back_button'><span> <= </span></div>
  </a>
  <h1>edit: <%= @category.name %></div></h1>
</section>


<!-- error if form is filled out incorrectly -->
<% @category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<!-- form to edit ingredient -->
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "update" %></li>
<% end %>
<!-- button to delete ingredient -->
<%= button_to "Delete", @category, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/categories/index.html.erb
<section class='heading_section'>
  <h1>Menu</h1>
</section>

<section class='form'>
  <h4>New category:</h4>
  <!-- error if form filled out incorrectly -->
  <% @category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>

  <!-- form to create new category -->
  <%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Create" %>
  <% end %>
</section>

<section class='buttons'>
<!-- list of all menu categories -->
  <% @categories.each do |category| %>
    <div class='button_group'>

      <!-- button to category submenu -->
      <a href='<%=category_items_path(category)%>'>
        <div class='menu_button'>
          <span><%= category.name %></span>
        </div>
      </a>

      <!-- button to edit category -->
      <a href='<%= edit_category_path(category) %>'>
        <div class='edit_button'>
          <span>edit</span>
        </div>
      </a>
    </div>
  <% end %>
</section>

app/views/foods/edit.html.erb
<!-- edit an ingredient -->
<h2>edit <%= @food.name %></h2>
<!-- error if form is filled out incorrectly -->
<% @food.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<!-- form to edit ingredient -->
<%= form_for @food do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :code %>
  <%= f.text_field :code %>

  <%= f.submit "update" %></li>
<% end %>
<!-- button to delete ingredient -->
<%= button_to "Delete", @food, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/foods/index.html.erb
<h2>All Ingredients</h2>

<!-- list of all ingredients available to the menu -->
<% @foods.each do |food| %>
  <li> <%= food.name %>: <%= food.code %></li>
  <%= link_to 'edit', edit_food_path(food) %>
<% end %>

<h4>Add Ingredient</h4>
<!-- error if form filled out incorrectly -->
<% @food.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<!-- form to add a new ingredient -->
<%= form_for @food do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :code %>
  <%= f.text_field :code %>

  <%= f.submit "add", method: :post %></li>
<% end %>

app/views/ingredients/edit.html.erb
<!-- edit an ingredient -->
<section class='heading_section'>
  <!-- back button -->
  <%= link_to '<=', ingredients_path, class: 'back_button' %>
  <!-- edit ingredient heading -->
  <h1>edit: <%= @ingredient.name %></div></h1>
</section>

<!-- shows error if form is filled out incorrectly -->
<% @ingredient.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<section class='form'>
  <!-- form to edit ingredient -->
  <%= form_for @ingredient do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :code %>
    <%= f.text_field :code %>

    <%= f.submit "update" %></li>
  <% end %>
  <!-- button to delete ingredient -->
  <%= button_to "Delete", @ingredient, method: :delete, data: {confirm: "Are you sure?"} %>
</section>

app/views/ingredients/index.html.erb
<!-- ingredients heading -->
<section class='heading_section'>
  <h1>Ingredients</h1>
</section>

<section class='form'>
  <!-- create new ingredient -->
  <h4>New ingredient:</h4>
  <!-- error if form filled out incorrectly -->
  <% @ingredient.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <!-- form to add a new ingredient -->
  <%= form_for @ingredient do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :code %>
    <%= f.text_field :code %>

    <%= f.submit "add", method: :post %></li>
  <% end %>
</section>

<section class='buttons all_ingredients'>
<!-- list of all ingredients available to the menu -->
  <% @ingredients.each do |ingredient| %>
    <!-- button to edit ingredient -->
    <%= link_to edit_ingredient_path(ingredient), class: 'menu_button' do %>
      <p class='edit'>EDIT</p>
      <%= ingredient.name %>
      <p class='code'><%= ingredient.code %></p>
    <% end %>
  <% end %>
</section>

app/views/items/edit.html.erb
<!-- form to edit menu item -->
<section class='heading_section'>
  <!-- back_button -->
  <%= link_to '<=', category_items_path(@category), class: 'back_button' %>
  <!-- edit menu item heading -->
  <h1>edit: <%= @item.name %></div></h1>
</section>

<!-- displays error if form is filled incorrectly -->
<% @item.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<section class='form'>
  <!-- form to edit item -->
  <%= form_for [@category, @item] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :code %>
    <%= f.text_field :code %>

    <%= f.submit "Update" %>
  <% end %>
  <!-- button to delete menu item -->
  <%= button_to "Delete", [@category, @item], method: :delete, data: {confirm: "Are you sure?"} %>
</section>

app/views/items/index.html.erb
<!-- Category submenu-->
<section class='heading_section'>
  <!-- back button -->
  <%= link_to '<=', categories_path, class: 'back_button' %>
  <!-- submenu heading -->
  <h1><%= @category.name %></div></h1>
</section>

<section class='form'>
  <h4>New menu item:</h4>
  <!-- display error if form is not filled correctly -->
  <% @item.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <!-- form to create new item -->
  <%= form_for [@category, @item] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :code %>
    <%= f.text_field :code %>

    <%= f.submit "Create" %>
  <% end %>
</section>

<section class='buttons'>
<!-- all submenu items -->
  <% @items.each do |item| %>
    <div class='button_group'>
      <!-- link to item show pages -->
      <%= link_to category_item_path(@category, item), class: 'menu_button' do %>
        <p class='name'><%= item.name %></p>
        <p class='code'><%= item.code %></p>
      <% end %>

      <!-- link to edit item -->
      <%= link_to 'edit', edit_category_item_path(@category, item), class: 'edit_button' %>
    </div>
  <% end %>
</section>

app/views/items/show.html.erb
<!-- menu item name -->
<section class='heading_section'>
  <!-- back button -->
  <%= link_to '<=', category_items_path(@category), class: 'back_button' %>
  <!-- item heading -->
  <h1><%= @item.name %></div></h1>

  <!-- form to add item to order -->
  <div class='add_order'>
    <%= form_for [@category, @item, @order] do |f| %>
      <%= f.label 'special request' %>
      <%= f.text_field :message %>

      <%= f.submit 'add to order', class: 'submit_button' %>
    <% end %>
  </div>
</section>

<!-- item's includes subheading -->
<h3>Remove ingredient:</h3>
<section class='form'>
  <!-- form to add include from list of ingredients -->
  <%= form_for [@category, @item, @include] do |f| %>
    <li><%= f.label 'add default ingredient' %>
    <%= f.collection_select(:ingredient_id, @ingredients, :id, :name) %>

    <%= f.submit "add" %></li>
  <% end %>
</section>

<section class='buttons remove_ingredients'>
  <!-- list of includes -->
  <% @item.ingredients.each do |ingredient| %>
    <div class='button_group'>

      <!-- tests if ingredient already removed -->
      <% if $modifications.include? 'NO ' + ingredient.name %>
        <!-- selected button -->
        <%= link_to category_item_include_remove_without_path(@category, @item, ingredient), class: "menu_button red", method: :delete do %>
          <p class='name'><%= ingredient.name %></p>
          <p class='code'><%= ingredient.code %></p>
        <% end %>
      <% else %>
        <!-- unselected button -->
        <%= link_to category_item_include_without_path(@category, @item, ingredient), class: "menu_button", method: :post do %>
          <p class='name'><%= ingredient.name %></p>
          <p class='code'><%= ingredient.code %></p>
        <% end %>
      <% end %>





      <!-- button to delete ingredient -->
      <%= link_to category_item_include_path(@category, @item, ingredient), class: "edit_button", method: :delete  do %>
        remove
      <% end %>
    </div>
  <% end %>
</section>

<h3>Add ingredient:</h3>
<section class='buttons add_ingredients'>
  <% @ingredients.each do |ingredient| %>

    <!-- tests if ingredient already added -->
    <% if $modifications.include? 'ADD ' + ingredient.name %>
      <!-- selected button -->
      <%= link_to category_item_include_remove_add_path(@category, @item, ingredient), class: "menu_button green", method: :delete do %>
        <p class='name'><%= ingredient.name %></p>
        <p class='code'><%= ingredient.code %></p>
      <% end %>
    <% else %>
      <!-- unselected button -->
      <%= link_to category_item_include_add_path(@category, @item, ingredient), class: "menu_button", method: :post do %>
        <p class='name'><%= ingredient.name %></p>
        <p class='code'><%= ingredient.code %></p>
      <% end %>
    <% end %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class='left'>
      <nav>
        <h1 class='main_head'>codePOS</h1>
        <!-- link to menu home -->
        <%= link_to 'Menu', categories_path, class: 'nav_button' %>

        <!-- link to manage ingredients -->
        <%= link_to 'Ingredients', ingredients_path, class: 'nav_button' %>
      </nav>


      <!-- display flash message -->
      <% flash.each do |type, message| %>
      <p class='flash'><%= message %></p>
      <% end %>

      <section class='yield'>
        <%= yield %>
      </section>
    </section>


    <section class='right'>
      <h1 class='order_head'>Order</h1>
        <ol class='order_list'>
          <% @orders.each do |order| %>
            <!-- delete item from order -->
            <li><%= link_to '(-)', order_path(order), method: :delete %> <%= order.item %></li>
                <ul>
                  <% if order.modification %>
                    <% order.modification.sort.each do |mod| %>
                      <li><%= mod.to_s %></li>
                    <% end %>
                    <% end %>
                  <% if order.message != "" %>
                    <li> REQUEST: <%= order.message %></li>
                  <% end %>
                </ul>
          <% end %>
        </ol>
    </section>

  </body>
</html>